package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMonitorLog<M extends BaseMonitorLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setObjectId(java.lang.Integer objectId) {
		set("objectId", objectId);
	}

	public java.lang.Integer getObjectId() {
		return get("objectId");
	}

	public void setAppName(java.lang.String appName) {
		set("appName", appName);
	}

	public java.lang.String getAppName() {
		return get("appName");
	}

	public void setAppStatus(java.lang.Integer appStatus) {
		set("appStatus", appStatus);
	}

	public java.lang.Integer getAppStatus() {
		return get("appStatus");
	}

	public void setAccessCount(java.lang.Integer accessCount) {
		set("accessCount", accessCount);
	}

	public java.lang.Integer getAccessCount() {
		return get("accessCount");
	}

}
