package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTksqd<M extends BaseTksqd<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSqdzt(java.lang.String sqdzt) {
		set("sqdzt", sqdzt);
	}

	public java.lang.String getSqdzt() {
		return get("sqdzt");
	}

	public void setXmmc(java.lang.String xmmc) {
		set("xmmc", xmmc);
	}

	public java.lang.String getXmmc() {
		return get("xmmc");
	}

	public void setSqr(java.lang.String sqr) {
		set("sqr", sqr);
	}

	public java.lang.String getSqr() {
		return get("sqr");
	}

	public void setKcdw(java.lang.String kcdw) {
		set("kcdw", kcdw);
	}

	public java.lang.String getKcdw() {
		return get("kcdw");
	}

	public void setKczgzh(java.lang.String kczgzh) {
		set("kczgzh", kczgzh);
	}

	public java.lang.String getKczgzh() {
		return get("kczgzh");
	}

	public void setKcdwdz(java.lang.String kcdwdz) {
		set("kcdwdz", kcdwdz);
	}

	public java.lang.String getKcdwdz() {
		return get("kcdwdz");
	}

	public void setSqsj(java.lang.String sqsj) {
		set("sqsj", sqsj);
	}

	public java.lang.String getSqsj() {
		return get("sqsj");
	}

	public void setKckz(java.lang.String kckz) {
		set("kckz", kckz);
	}

	public java.lang.String getKckz() {
		return get("kckz");
	}

	public void setXmxz(java.lang.String xmxz) {
		set("xmxz", xmxz);
	}

	public java.lang.String getXmxz() {
		return get("xmxz");
	}

	public void setZmj(java.lang.String zmj) {
		set("zmj", zmj);
	}

	public java.lang.String getZmj() {
		return get("zmj");
	}

	public void setZj(java.lang.String zj) {
		set("zj", zj);
	}

	public java.lang.String getZj() {
		return get("zj");
	}

	public void setFddbr(java.lang.String fddbr) {
		set("fddbr", fddbr);
	}

	public java.lang.String getFddbr() {
		return get("fddbr");
	}

	public void setDh(java.lang.String dh) {
		set("dh", dh);
	}

	public java.lang.String getDh() {
		return get("dh");
	}

	public void setGzrwjzymd(java.lang.String gzrwjzymd) {
		set("gzrwjzymd", gzrwjzymd);
	}

	public java.lang.String getGzrwjzymd() {
		return get("gzrwjzymd");
	}

	public void setBgsj(java.lang.String bgsj) {
		set("bgsj", bgsj);
	}

	public java.lang.String getBgsj() {
		return get("bgsj");
	}

	public void setZxlx(java.lang.String zxlx) {
		set("zxlx", zxlx);
	}

	public java.lang.String getZxlx() {
		return get("zxlx");
	}

	public void setYxq(java.lang.String yxq) {
		set("yxq", yxq);
	}

	public java.lang.String getYxq() {
		return get("yxq");
	}

	public void setKcsyfljjn(java.lang.String kcsyfljjn) {
		set("kcsyfljjn", kcsyfljjn);
	}

	public java.lang.String getKcsyfljjn() {
		return get("kcsyfljjn");
	}

	public void setZxly(java.lang.String zxly) {
		set("zxly", zxly);
	}

	public java.lang.String getZxly() {
		return get("zxly");
	}

	public void setDjjgglyj(java.lang.String djjgglyj) {
		set("djjgglyj", djjgglyj);
	}

	public java.lang.String getDjjgglyj() {
		return get("djjgglyj");
	}

	public void setZxsj(java.lang.String zxsj) {
		set("zxsj", zxsj);
	}

	public java.lang.String getZxsj() {
		return get("zxsj");
	}

	public void setZrsqr(java.lang.String zrsqr) {
		set("zrsqr", zrsqr);
	}

	public java.lang.String getZrsqr() {
		return get("zrsqr");
	}

	public void setZrsqrdz(java.lang.String zrsqrdz) {
		set("zrsqrdz", zrsqrdz);
	}

	public java.lang.String getZrsqrdz() {
		return get("zrsqrdz");
	}

	public void setZrsqrdh(java.lang.String zrsqrdh) {
		set("zrsqrdh", zrsqrdh);
	}

	public java.lang.String getZrsqrdh() {
		return get("zrsqrdh");
	}

	public void setZrsqrkhyh(java.lang.String zrsqrkhyh) {
		set("zrsqrkhyh", zrsqrkhyh);
	}

	public java.lang.String getZrsqrkhyh() {
		return get("zrsqrkhyh");
	}

	public void setZh(java.lang.String zh) {
		set("zh", zh);
	}

	public java.lang.String getZh() {
		return get("zh");
	}

	public void setKcgzzyjzqk(java.lang.String kcgzzyjzqk) {
		set("kcgzzyjzqk", kcgzzyjzqk);
	}

	public java.lang.String getKcgzzyjzqk() {
		return get("kcgzzyjzqk");
	}

	public void setSrr(java.lang.String srr) {
		set("srr", srr);
	}

	public java.lang.String getSrr() {
		return get("srr");
	}

	public void setSrrdz(java.lang.String srrdz) {
		set("srrdz", srrdz);
	}

	public java.lang.String getSrrdz() {
		return get("srrdz");
	}

	public void setSrrdh(java.lang.String srrdh) {
		set("srrdh", srrdh);
	}

	public java.lang.String getSrrdh() {
		return get("srrdh");
	}

	public void setSrrkhyh(java.lang.String srrkhyh) {
		set("srrkhyh", srrkhyh);
	}

	public java.lang.String getSrrkhyh() {
		return get("srrkhyh");
	}

	public void setSrmd(java.lang.String srmd) {
		set("srmd", srmd);
	}

	public java.lang.String getSrmd() {
		return get("srmd");
	}

	public void setSjzgbmyj(java.lang.String sjzgbmyj) {
		set("sjzgbmyj", sjzgbmyj);
	}

	public java.lang.String getSjzgbmyj() {
		return get("sjzgbmyj");
	}

	public void setDcmj(java.lang.String dcmj) {
		set("dcmj", dcmj);
	}

	public java.lang.String getDcmj() {
		return get("dcmj");
	}

	public void setDlwz(java.lang.String dlwz) {
		set("dlwz", dlwz);
	}

	public java.lang.String getDlwz() {
		return get("dlwz");
	}

	public void setSqnx(java.lang.String sqnx) {
		set("sqnx", sqnx);
	}

	public java.lang.String getSqnx() {
		return get("sqnx");
	}

	public void setDdgzrwjzymd(java.lang.String ddgzrwjzymd) {
		set("ddgzrwjzymd", ddgzrwjzymd);
	}

	public java.lang.String getDdgzrwjzymd() {
		return get("ddgzrwjzymd");
	}

	public void setZyswgzl(java.lang.String zyswgzl) {
		set("zyswgzl", zyswgzl);
	}

	public java.lang.String getZyswgzl() {
		return get("zyswgzl");
	}

	public void setZjly(java.lang.String zjly) {
		set("zjly", zjly);
	}

	public java.lang.String getZjly() {
		return get("zjly");
	}

	public void setDdkcdw(java.lang.String ddkcdw) {
		set("ddkcdw", ddkcdw);
	}

	public java.lang.String getDdkcdw() {
		return get("ddkcdw");
	}

	public void setNjkckz(java.lang.String njkckz) {
		set("njkckz", njkckz);
	}

	public java.lang.String getNjkckz() {
		return get("njkckz");
	}

	public void setKcmj(java.lang.String kcmj) {
		set("kcmj", kcmj);
	}

	public java.lang.String getKcmj() {
		return get("kcmj");
	}

	public void setGtzydcf(java.lang.String gtzydcf) {
		set("gtzydcf", gtzydcf);
	}

	public java.lang.String getGtzydcf() {
		return get("gtzydcf");
	}

	public void setKczyjcf(java.lang.String kczyjcf) {
		set("kczyjcf", kczyjcf);
	}

	public java.lang.String getKczyjcf() {
		return get("kczyjcf");
	}

	public void setGnqytr(java.lang.String gnqytr) {
		set("gnqytr", gnqytr);
	}

	public java.lang.String getGnqytr() {
		return get("gnqytr");
	}

	public void setZyczbt(java.lang.String zyczbt) {
		set("zyczbt", zyczbt);
	}

	public java.lang.String getZyczbt() {
		return get("zyczbt");
	}

	public void setKs(java.lang.String ks) {
		set("ks", ks);
	}

	public java.lang.String getKs() {
		return get("ks");
	}

	public void setCs(java.lang.String cs) {
		set("cs", cs);
	}

	public java.lang.String getCs() {
		return get("cs");
	}

	public void setQj(java.lang.String qj) {
		set("qj", qj);
	}

	public java.lang.String getQj() {
		return get("qj");
	}

}
