package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMonitorObjectConfig<M extends BaseMonitorObjectConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAppName(java.lang.String appName) {
		set("appName", appName);
	}

	public java.lang.String getAppName() {
		return get("appName");
	}

	public void setAppUrl(java.lang.String appUrl) {
		set("appUrl", appUrl);
	}

	public java.lang.String getAppUrl() {
		return get("appUrl");
	}

	public void setAppDesc(java.lang.String appDesc) {
		set("appDesc", appDesc);
	}

	public java.lang.String getAppDesc() {
		return get("appDesc");
	}

	public void setAppStatus(java.lang.Integer appStatus) {
		set("appStatus", appStatus);
	}

	public java.lang.Integer getAppStatus() {
		return get("appStatus");
	}

	public void setAccessCountMin(java.lang.Integer accessCountMin) {
		set("accessCountMin", accessCountMin);
	}

	public java.lang.Integer getAccessCountMin() {
		return get("accessCountMin");
	}

	public void setAccessCountMax(java.lang.Integer accessCountMax) {
		set("accessCountMax", accessCountMax);
	}

	public java.lang.Integer getAccessCountMax() {
		return get("accessCountMax");
	}

}
