package com.demo.common.model;

import com.demo.common.model.base.BaseMonitorLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MonitorLog extends BaseMonitorLog<MonitorLog> {
	public static final MonitorLog dao = new MonitorLog();
}
