package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseMonitorLog;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MonitorLog extends BaseMonitorLog<MonitorLog> {
	public static final MonitorLog dao = new MonitorLog();
	
	public Page<MonitorLog> paginate1(int pageNumber, int pageSize, String appId) {
        return paginate(pageNumber, pageSize, "select *", "from monitor_log where objectId="+ appId +" order by id desc");
    }
	
	public List<MonitorLog> getLastLog(String appIds){
	    String sql = "select * from monitor_log ml "
	    +" join( "
	    +" select objectId,max(id) id from monitor_log  "
	    +" where objectId in("+ appIds +") "
	    +" group by objectId) t on ml.id = t.id ";
	    return find(sql);
	}
}
