package com.demo.common.model;

import com.demo.common.model.base.BaseTksqd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tksqd extends BaseTksqd<Tksqd> {
	public static final Tksqd dao = new Tksqd();
}
